### PR TITLE
Fix error when user()->first() is null in DiscussionBestAnswerPage.php

### PR DESCRIPTION
**Pull request by alexisrazok**
Fix to avoid error message when $discussion->user()->first() is null.

### CODE REVIEW

**Comment by jaspervriends** [comment]
Hey @alexisrazok , thanks for the PR! I see Clark just replied with a different kind of solution as well in #101 (he doesn't have a PR), would you be able to check if that works and change your PR? Then I'll go ahead and merge the PR for you 😄 

https://github.com/v17development/flarum-seo/issues/101

**Comment by alexisrazok** [comment]
yes @jaspervriends it works, I made a mistake in the other patch but this patch is right. Thank you.

**Comment by rafaucau** [comment]
As this has not been merged (yet), I have opened a pull request which will contain a number of fixes, including this pull request.
https://github.com/v17development/flarum-seo/pull/102

**Comment by jaspervriends** [comment]
Thanks for the PR! It has been merged, together with #102 's changes!

**Pull request closed without merging**
