### PR TITLE
Update PageListener.php

### PR DESCRIPTION
**Pull request by os555**
Edit function to get dynamic og:image if post has images.

### CODE REVIEW

**Comment by os555** [comment]
Hi Jasper I am trying to created a new function for setOgimage please review again. :)

**Comment by nitaaikumar** [comment]
i think @os555 has fixed it. please @jaspervriends could you approve this or something similar so that we can get a proper og:image to show up on facebook, twitter, whatsapp, telegram, etc. for each of our flarum discussions. Thanks.

**Comment by nitaaikumar** [comment]
Thanks @jaspervriends. For me even this commit is not specifying a clear og:image url for facebook, twitter, whatsapp, telegram, etc. if you could please check it on your forum and further fix or fine tune it to make it work consistently for the og:image, i will be so grateful.

**Comment by jaspervriends** [comment]
@nitaaikumar I've updated the extension to version `1.1`, it should work now. Are you able to try it?

**Comment by nitaaikumar** [comment]
Thank you @jaspervriends. The og:image is showing up now on Facebook, Telegram etc. Thank you so much for finally fixing this long pending bug. As they say, all is well that ends well.

**Pull request merged**
